[docker]
host = "localhost"

[core]
daiTokenContractAddress = "0x642d2b84a32a9a92fec78ceaa9488388b3704898"
dataUnionFactorySidechainCreationBlock = 0
dataUnionPublishMemberLimit = 1
marketplaceContractAddress = "0xF1371c0f40528406dc4f4cAf89924eA9Da49E866"
platformOriginUrl = ""
streamrUrl = ""
uniswapAdaptorContractAddress = "0xE4eA76e830a659282368cA2e7E4d18C4AE52D8B3"
web3TransactionConfirmationBlocks = 1

[[core.storageNodes]]
name = "Local (broker-node-storage-1)"
address = "0xde1112f631486CfC759A50196853011528bC5FA0"

[client]
graphUrl = ":8000/subgraphs/name/streamr-dev/network-contracts"
restUrl = "/api/v2"
streamRegistryChainAddress = "0x6cCdd5d866ea766f6DF5965aA98DeCCD629ff222"
streamrNodeAddress = "0xFCAd0B19bB29D4674531d6f115237E16AfCE377c"
streamStorageRegistryChainAddress = "0xd04af489677001444280366Dd0885B03dAaDe71D"

[client.dataUnion]
factoryMainnetAddress = "0x4bbcBeFBEC587f6C4AF9AF9B48847caEa1Fe81dA"
templateMainnetAddress = "0x7bFBAe10AE5b5eF45e2aC396E0E605F6658eF3Bc"
factorySidechainAddress = "0x4A4c4759eb3b7ABee079f832850cD3D0dC48D927"
templateSidechainAddress = "0x36afc8c9283CC866b8EB6a61C6e6862a83cd6ee8"

[client.mainchain]
chainId = 8995
dataTokenAddress = "0xbAA81A0179015bE47Ad439566374F2Bae098686F"

[client.mainchain.rpc]
url = ":8545"

[client.sidechain]
dataTokenAddress = "0x73Be21733CC5D08e1a14Ea9a399fb27DB3BEf8fF"

[client.dataUnionChain.rpc]
chainId = 8997
url = ":8546"

[client.streamRegistryChain.rpc]
chainId = 8997
url = ":8546"

[[client.network.trackers]]
id = "0xb9e7cEBF7b03AE26458E32a059488386b05798e8"
wsUrl = ":30301"
httpUrl = ":30301"

[[client.network.trackers]]
id = "0x0540A3e144cdD81F402e7772C76a5808B71d2d30"
wsUrl = ":30302"
httpUrl = ":30302"

[[client.network.trackers]]
id = "0xf2C195bE194a2C91e93Eacb1d6d55a00552a85E2"
wsUrl = ":30303"
httpUrl = ":30303"
